<?php

namespace LucasGiovanny\LaravelPrestashop\Resources;

use LucasGiovanny\LaravelPrestashop\Persistance;
use LucasGiovanny\LaravelPrestashop\Query;

class OrderDetails extends Resource
{
    use Query\Searchable;
    use Persistance\Storable;

    protected static $rules = [
        'id_order' => 'required|numeric',
        'product_id' => 'nullable|numeric',
        'product_attribute_id' => 'nullable|numeric',
        'product_quantity_reinjected' => 'nullable|numeric',
        'group_reduction' => 'nullable|float',
        'discount_quantity_applied' => 'nullable|numeric',
        'download_hash' => 'nullable|string',
        'download_deadline' => 'nullable|date',
        'id_order_invoice' => 'nullable|numeric',
        'id_warehouse' => 'required|numeric',
        'id_shop' => 'required|numeric',
        'id_customization' => 'nullable|numeric',
        'product_name' => 'required|string',
        'product_quantity' => 'required|numeric',
        'product_quantity_in_stock' => 'nullable|numeric',
        'product_quantity_return' => 'nullable|numeric',
        'product_quantity_refunded' => 'nullable|numeric',
        'product_price' => 'required|float',
        'reduction_percent' => 'nullable|float',
        'reduction_amount' => 'nullable|float',
        'reduction_amount_tax_incl' => 'nullable|float',
        'reduction_amount_tax_excl' => 'nullable|float',
        'product_quantity_discount' => 'nullable|numeric',
        'product_ean13' => 'nullable|string',
        'product_isbn' => 'nullable|string',
        'product_upc' => 'nullable|string',
        'product_mpn' => 'nullable|string',
        'product_reference' => 'nullable|string',
        'product_supplier_reference' => 'nullable|string',
        'product_weight' => 'nullable|float',
        'tax_computation_method' => 'nullable|numeric',
        'id_tax_rules_group' => 'nullable|numeric',
        'ecotax' => 'nullable|float',
        'ecotax_tax_rate' => 'nullable|float',
        'download_nb' => 'nullable|numeric',
        'unit_price_tax_incl' => 'nullable|float',
        'unit_price_tax_excl' => 'nullable|float',
        'total_price_tax_incl' => 'nullable|float',
        'total_price_tax_excl' => 'nullable|float',
        'total_shipping_price_tax_excl' => 'nullable|float',
        'total_shipping_price_tax_incl' => 'nullable|float',
        'purchase_supplier_price' => 'nullable|float',
        'original_product_price' => 'nullable|float',
        'original_wholesale_price' => 'nullable|float',
        'total_refunded_tax_excl' => 'nullable|float',
        'total_refunded_tax_incl' => 'nullable|float',
        'associations' => 'nullable|array',
    ];

    protected static $messages = [
        'id_order.required' => 'The id_order is required.',
        'id_order.numeric' => 'The Order id must be numeric.',
        'id_warehouse.required' => 'The Warehouse id is required.',
        'id_warehouse.numeric' => 'The Warehouse id must be numeric.',
        'id_shop.required' => 'The Shop id is required.',
        'id_shop.numeric' => 'The Shop id must be numeric.',
        'product_name.required' => 'The Product name field is required.',
        'product_name.string' => 'The Product name must be a string.',
        'product_quantity.required' => 'The Product quantity field is required.',
        'product_quantity.numeric' => 'The Product quantity must be numeric.',
        'product_price.required' => 'The Product price is required.',
        'product_price.float' => 'The Product price must be a float.',
    ];

    protected array $fillable = [
        'id',
        'id_order',
        'product_id',
        'product_attribute_id',
        'product_quantity_reinjected',
        'group_reduction',
        'discount_quantity_applied',
        'download_hash',
        'download_deadline',
        'id_order_invoice',
        'id_warehouse',
        'id_shop',
        'id_customization',
        'product_name',
        'product_quantity',
        'product_quantity_in_stock',
        'product_quantity_return',
        'product_quantity_refunded',
        'product_price',
        'reduction_percent',
        'reduction_amount',
        'reduction_amount_tax_incl',
        'reduction_amount_tax_excl',
        'reduction_amount_tax_excl',
        'product_quantity_discount',
        'product_ean13',
        'product_isbn',
        'product_upc',
        'product_mpn',
        'product_reference',
        'product_supplier_reference',
        'product_weight',
        'tax_computation_method',
        'id_tax_rules_group',
        'ecotax',
        'ecotax_tax_rate',
        'download_nb',
        'unit_price_tax_incl',
        'unit_price_tax_excl',
        'total_price_tax_incl',
        'total_price_tax_excl',
        'total_shipping_price_tax_excl',
        'total_shipping_price_tax_incl',
        'purchase_supplier_price',
        'original_product_price',
        'original_wholesale_price',
        'total_refunded_tax_excl',
        'total_refunded_tax_incl',
        'associations',
    ];

    protected $xml_header = 'order_detail';

    protected $url = 'order_details';
}
